server:
  port: 9999

spring:
  profiles:
    active: tes
  application:
    name: BIGDATA-AUTH-SERVICE
  main:
    allow-bean-definition-overriding: true  #表示后发现的bean会覆盖之前相同名称的bean
  devtools:
    restart:
      enabled: true #是否支持热部署

secure:
  ignored:
    urls: #安全路径白名单
      - /ignore/**
      - /api/v1/auth/login/**
      - /api/v1/auth/logout/**
      - /api/v1/auth/register/**
      - /api/v1/auth/refresh/**
      - /**/druid/**
      - /**/actuator/**
      - /home/**
      - /**/home/**
    resources:
      - /
      - /static/**
      - /img/**
      - /swagger-ui.html
      - /doc.html
      - /login.html
      - /webjars/**
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/*.html
      - /favicon.ico
      - /webjars/springfox-swagger-ui/**